version: '3'
services:
  chatbot:
    image: 7940image2
    # missing instructions for setting environment variable
    # missing instructions for setting the entrypoint and/or command
    #--env ACCESS_TOKEN=1663811015:AAFh1HmZ04FAXQznTj8A8kF1MwbIaKCck9I --env HOST=redis-11288.c93.us-east-1-3.ec2.cloud.redislabs.com --env PASSWORD=Cq40u0ENJAlfOFzJZnybGc1DelwXq8tB --env REDISPORT=11288
    #python chatbot.py